"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, ArrowRight, CalendarClock, Check, CheckCircle2, ClipboardCheck, ClockAlert, FileClock, FileText, History, House, Loader2, Mail, MessageCircleQuestion, PencilLine, Settings, ShieldCheck, UserRound, UsersRound } from "lucide-react";
import type { DashboardData, Project, Schedule } from "@/types/dashboard";
import { apiFetch, formatDate, formatFullDate, isOverdue } from "@/lib/client-utils";
import { EmptyState } from "@/components/DashboardShell";
import { Metric, PageHeader, ProgressBar, ReportCard, StatusBadge, TaskCard } from "@/components/ui/Common";

export function AdminView({ data, project, tab, onTab }: { data: DashboardData; project: Project; tab: string; onTab: (id: string) => void }) {
  const router = useRouter(); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const pending = data.reports.filter((report) => report.approvalStatus === "PENDING");
  const delayed = data.projects.flatMap((p) => p.schedules.filter((s) => s.status === "DELAYED").map((s) => ({ ...s, projectName: p.name })));
  const priorityTasks = data.tasks.filter((task) => !["RESOLVED", "COMPLETED"].includes(task.status) && (task.priority === "URGENT" || isOverdue(task.dueAt) || task.status === "UNCHECKED" || task.status === "QUESTIONING"));
  const projectTasks = data.tasks.filter((task) => task.projectId === project.id);
  async function bulkApprove() { if (!selected.length) return; setBusy(true); setError(""); try { const result = await apiFetch("/api/reports/bulk-approve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: selected }) }); setSelected([]); router.refresh(); window.alert(`${result.count}件を承認しました`); } catch (err) { setError(err instanceof Error ? err.message : "一括承認できませんでした"); } finally { setBusy(false); } }

  if (tab === "approvals") return <><PageHeader eyebrow="APPROVALS" title="未承認の現場報告" text="写真と作業内容を確認し、施主への公開可否を判断します。" actions={selected.length ? <button className="button primary" onClick={bulkApprove} disabled={busy}>{busy ? <Loader2 className="spin" size={17} /> : <Check size={17} />}{selected.length}件を一括承認</button> : undefined} />{error && <div className="alert error">{error}</div>}<div className="report-grid admin-reports">{pending.map((report) => <ReportCard key={report.id} report={report} admin selected={selected.includes(report.id)} onSelect={(checked) => setSelected((current) => checked ? [...current, report.id] : current.filter((id) => id !== report.id))} />)}</div>{!pending.length && <EmptyState icon={ClipboardCheck} title="承認待ちはありません" text="すべての現場報告を確認済みです。" />}</>;
  if (tab === "tasks") return <><PageHeader eyebrow="TASK CENTER" title="質問・現場依頼" text="未回答・期限超過・緊急の項目を優先して表示しています。" /><div className="filter-summary"><span><AlertTriangle size={16} />優先対応 <strong>{priorityTasks.length}</strong>件</span><span>選択中：{project.name}</span></div><div className="task-list">{projectTasks.map((task) => <TaskCard key={task.id} task={task} user={data.user} workers={data.workers} />)}</div>{!projectTasks.length && <EmptyState title="質問・依頼はありません" text="施主や現場からのタスクがここに表示されます。" />}</>;
  if (tab === "members") return <DirectoryView title="メンバー" eyebrow="MEMBERS" text="施工チームと担当職種を確認します。" items={data.workers.map((worker) => ({ id: worker.id, name: worker.name, meta: worker.trade || (worker.role === "ADMIN" ? "管理者" : "担当者"), role: worker.role === "ADMIN" ? "ADMIN" : "STAFF" }))} />;
  if (tab === "clients") return <DirectoryView title="施主" eyebrow="CLIENTS" text="各プロジェクトの施主と進捗を確認します。" items={data.projects.map((item) => ({ id: item.id, name: item.owner.name, meta: `${item.name} / ${item.address}`, role: "CLIENT" }))} />;
  if (tab === "documents") return <AdminDocuments />;
  if (tab === "settings") return <AdminSettings />;
  if (tab === "schedule") return <ScheduleView data={data} project={project} />;
  if (tab === "audit") return <AuditView data={data} />;

  return <>
    <PageHeader eyebrow="OVERVIEW" title={`こんにちは、${data.user.name.split(" ")[0]}さん。`} text={`${formatFullDate(new Date().toISOString())}｜プロジェクトの今と、確認が必要なこと。`} actions={<span className="admin-secure"><ShieldCheck size={17} />ADMIN</span>} />
    <div className="metric-grid"><Metric label="承認待ち" value={pending.length} note="現場報告" icon={ClipboardCheck} tone="amber" /><Metric label="遅延工程" value={delayed.length} note="要スケジュール確認" icon={ClockAlert} tone="red" /><Metric label="未回答質問" value={data.tasks.filter((t) => t.type === "OWNER_QUESTION" && t.status === "QUESTIONING").length} note="施主から" icon={MessageCircleQuestion} tone="blue" /><Metric label="現場依頼" value={data.tasks.filter((t) => t.type === "SITE_REQUEST" && !["COMPLETED"].includes(t.status)).length} note="未完了" icon={AlertTriangle} tone="green" /></div>
    {priorityTasks.length > 0 && <section className="priority-board"><div className="priority-title"><span><AlertTriangle size={20} /></span><div><p className="eyebrow">ACTION REQUIRED</p><h2>優先して対応してください</h2></div><b>{priorityTasks.length}</b></div><div className="priority-items">{priorityTasks.slice(0, 4).map((task) => <button key={task.id} onClick={() => onTab("tasks")}><span className={`priority-mark ${task.type === "OWNER_QUESTION" ? "blue" : "orange"}`}>{task.type === "OWNER_QUESTION" ? <MessageCircleQuestion /> : <AlertTriangle />}</span><span><small>{task.project.name}・{task.type === "OWNER_QUESTION" ? "施主質問" : task.trade || "現場依頼"}</small><strong>{task.title}</strong><small>{isOverdue(task.dueAt) ? "期限を超過しています" : task.dueAt ? `${formatDate(task.dueAt)}まで` : "新着"}</small></span><ArrowRight size={18} /></button>)}</div></section>}
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">PROJECTS</p><h2>現場の進み具合</h2></div><span>{data.projects.length}現場</span></div><div className="project-table">{data.projects.map((item) => { const monthItems = item.schedules.filter((s) => s.level === "MONTH"); const progress = monthItems.length ? Math.round(monthItems.reduce((sum, s) => sum + s.progress, 0) / monthItems.length) : 0; const late = item.schedules.filter((s) => s.status === "DELAYED").length; return <article key={item.id}><div className="project-icon"><House size={21} /></div><div className="project-name"><small>{item.code}</small><strong>{item.name}</strong><span>{item.address}</span></div><div className="project-owner"><UsersRound size={15} />{item.owner.name}</div><div className="project-progress"><ProgressBar value={progress} tone={late ? "orange" : "green"} />{late > 0 && <small className="danger-text">遅延工程 {late}件</small>}</div><StatusBadge status={late ? "DELAYED" : progress === 100 ? "DONE" : "IN_PROGRESS"} /></article>; })}</div></section>
    <div className="two-columns admin-bottom"><section className="section-block"><div className="section-heading"><div><p className="eyebrow">PENDING</p><h2>新着の承認待ち</h2></div><button className="button text" onClick={() => onTab("approvals")}>すべて見る</button></div>{pending.slice(0, 3).map((report) => <div className="approval-row" key={report.id}><div>{report.photos[0] ? <img src={`/api/photos/${report.photos[0].id}`} alt="現場写真" /> : <span />}</div><span><small>{report.project.name}</small><strong>{report.scheduleItem.title}</strong><small>{report.author.name}・{formatDate(report.createdAt, true)}</small></span><StatusBadge status="PENDING" /></div>)}{!pending.length && <EmptyState icon={CheckCircle2} title="確認済みです" text="新しい承認待ちはありません。" />}</section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">DELAYS</p><h2>遅延工程</h2></div><button className="button text" onClick={() => onTab("schedule")}>工程表へ</button></div>{delayed.slice(0, 4).map((item) => <div className="delay-row" key={item.id}><span><CalendarClock /></span><div><small>{item.projectName}</small><strong>{item.title}</strong><p>変更後：{formatDate(item.currentStart)}〜{formatDate(item.currentEnd)}</p></div><b>{item.progress}%</b></div>)}</section></div>
  </>;
}

function ScheduleView({ data, project }: { data: DashboardData; project: Project }) {
  const router = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const rows = useMemo(() => project.schedules, [project.schedules]);
  async function change(item: Schedule) {
    const start = window.prompt("変更後の開始日（YYYY-MM-DD）", item.currentStart.slice(0, 10)); if (!start) return;
    const end = window.prompt("変更後の終了日（YYYY-MM-DD）", item.currentEnd.slice(0, 10)); if (!end) return;
    const reason = window.prompt("変更理由（必須）"); if (!reason) return;
    setBusy(item.id); setError(""); try { await apiFetch(`/api/schedules/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ currentStart: start, currentEnd: end, reason }) }); router.refresh(); } catch (err) { setError(err instanceof Error ? err.message : "変更できませんでした"); } finally { setBusy(""); }
  }
  return <><PageHeader eyebrow="SCHEDULE" title="工程表と変更履歴" text={`${project.name}｜当初予定は保持したまま、変更後の予定を管理します。`} />{error && <div className="alert error">{error}</div>}<section className="schedule-board"><div className="schedule-head"><span>工程</span><span>当初予定</span><span>現在予定</span><span>進捗</span><span>状態</span><span /></div>{rows.map((item) => { const changed = item.originalStart.slice(0, 10) !== item.currentStart.slice(0, 10) || item.originalEnd.slice(0, 10) !== item.currentEnd.slice(0, 10); return <div className={`schedule-row level-${item.level.toLowerCase()}`} key={item.id}><div><span className="tree-mark" /><strong>{item.title}</strong>{item.trade && <small>{item.trade}</small>}</div><span>{formatDate(item.originalStart)}〜{formatDate(item.originalEnd)}</span><span className={changed ? "changed-date" : ""}>{formatDate(item.currentStart)}〜{formatDate(item.currentEnd)}{changed && <small>変更あり</small>}</span><ProgressBar value={item.progress} tone={item.status === "DELAYED" ? "orange" : "green"} /><StatusBadge status={item.status} /><button className="icon-button" onClick={() => change(item)} disabled={busy === item.id} aria-label={`${item.title}の予定を変更`}>{busy === item.id ? <Loader2 className="spin" size={17} /> : <PencilLine size={17} />}</button></div>; })}</section><section className="section-block change-history"><div className="section-heading"><div><p className="eyebrow">CHANGE LOG</p><h2>予定変更履歴</h2></div></div>{data.changes.filter((c) => c.project.name === project.name).map((change) => <article key={change.id}><span><FileClock size={18} /></span><div><h3>{change.scheduleItem.title}</h3><p><s>{formatDate(change.previousStart)}〜{formatDate(change.previousEnd)}</s><ArrowRight size={14} /> <strong>{formatDate(change.newStart)}〜{formatDate(change.newEnd)}</strong></p><small>理由：{change.reason}｜{change.changedBy.name}・{formatDate(change.createdAt, true)}</small></div></article>)}</section></>;
}

function DirectoryView({ title, eyebrow, text, items }: { title: string; eyebrow: string; text: string; items: { id: string; name: string; meta: string; role: string }[] }) {
  return <><PageHeader eyebrow={eyebrow} title={title} text={text} /><section className="auri-directory">{items.map((item, index) => <article key={item.id}><span className="auri-directory-index">{String(index + 1).padStart(2, "0")}</span><span className="auri-directory-avatar"><UserRound size={20} /></span><div><strong>{item.name}</strong><p>{item.meta}</p></div><span className="auri-directory-role">{item.role}</span><button className="icon-button" aria-label={`${item.name}へ連絡`}><Mail size={17} /></button></article>)}</section>{!items.length && <EmptyState icon={UsersRound} title={`${title}はいません`} text="登録されるとここに表示されます。" />}</>;
}

function AdminDocuments() {
  const categories = ["契約書", "図面", "仕様書", "見積書", "保証書", "取扱説明書"];
  return <><PageHeader eyebrow="DOCUMENTS" title="書類と図面" text="案件に関わる資料を、カテゴリと更新履歴で整理します。" /><section className="auri-document-list">{categories.map((name, index) => <article key={name}><span>{String(index + 1).padStart(2, "0")}</span><FileText size={20} /><div><strong>{name}</strong><small>共有ファイルはまだありません</small></div><em>EMPTY</em></article>)}</section></>;
}

function AdminSettings() {
  return <><PageHeader eyebrow="SETTINGS" title="組織と権限" text="Auri+のアクセス方針と公開ルールを確認します。" /><section className="auri-settings"><article><Settings size={22} /><div><p>AUTHENTICATION</p><h2>ひとつの認証</h2><span>すべての利用者は同じログイン画面を使用し、Roleで表示先を切り替えます。</span></div></article><article><ShieldCheck size={22} /><div><p>PROJECT ACCESS</p><h2>現場ごとの閲覧権限</h2><span>STAFFとCLIENTは、割り当てられたProjectだけをサーバー側で取得します。</span></div></article><article><CheckCircle2 size={22} /><div><p>PUBLICATION</p><h2>承認後に公開</h2><span>現場報告はADMINの承認後にのみ、CLIENTへ公開されます。</span></div></article></section></>;
}

const auditNames: Record<string, string> = { LOGIN: "ログイン", LOGOUT: "ログアウト", CREATE_REPORT: "現場報告を登録", APPROVE_REPORT: "報告を承認", REJECT_REPORT: "報告を差し戻し", CREATE_TASK: "タスクを登録", UPDATE_TASK: "タスクを更新", ADD_TASK_MESSAGE: "返信を追加", UPDATE_SCHEDULE: "工程を更新", SEED_CREATED: "初期データを作成" };
function AuditView({ data }: { data: DashboardData }) { return <><PageHeader eyebrow="AUDIT LOG" title="監査履歴" text="誰が、いつ、何を変更したかを確認できます。履歴は削除されません。" /><section className="audit-list">{data.auditLogs.map((log) => <article key={log.id}><span className="audit-icon"><History size={18} /></span><div><strong>{auditNames[log.action] || log.action}</strong><p>{log.user?.name || "システム"} ・ {log.entityType} / {log.entityId.slice(-8)}</p></div><time>{formatDate(log.createdAt, true)}</time></article>)}</section>{!data.auditLogs.length && <EmptyState icon={History} title="監査履歴はありません" text="操作を行うとここに記録されます。" />}</>; }
