PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS "User" (
  "id" TEXT NOT NULL PRIMARY KEY, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "name" TEXT NOT NULL,
  "role" TEXT NOT NULL, "trade" TEXT, "active" INTEGER NOT NULL DEFAULT 1,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, "deletedAt" DATETIME
);
CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");

CREATE TABLE IF NOT EXISTS "Project" (
  "id" TEXT NOT NULL PRIMARY KEY, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "address" TEXT NOT NULL, "ownerId" TEXT NOT NULL,
  "startDate" DATETIME NOT NULL, "plannedEndDate" DATETIME NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL, "deletedAt" DATETIME, FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "Project_code_key" ON "Project"("code");

CREATE TABLE IF NOT EXISTS "ProjectMember" (
  "projectId" TEXT NOT NULL, "userId" TEXT NOT NULL, PRIMARY KEY ("projectId", "userId"),
  FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "ScheduleItem" (
  "id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "parentId" TEXT, "level" TEXT NOT NULL, "title" TEXT NOT NULL,
  "description" TEXT, "trade" TEXT, "originalStart" DATETIME NOT NULL, "originalEnd" DATETIME NOT NULL,
  "currentStart" DATETIME NOT NULL, "currentEnd" DATETIME NOT NULL, "progress" INTEGER NOT NULL DEFAULT 0,
  "status" TEXT NOT NULL DEFAULT 'NOT_STARTED', "sortOrder" INTEGER NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, "deletedAt" DATETIME,
  FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("parentId") REFERENCES "ScheduleItem"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "ScheduleChange" (
  "id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "scheduleItemId" TEXT NOT NULL, "changedById" TEXT NOT NULL,
  "previousStart" DATETIME NOT NULL, "previousEnd" DATETIME NOT NULL, "newStart" DATETIME NOT NULL, "newEnd" DATETIME NOT NULL,
  "reason" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("scheduleItemId") REFERENCES "ScheduleItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("changedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Report" (
  "id" TEXT NOT NULL PRIMARY KEY, "projectId" TEXT NOT NULL, "scheduleItemId" TEXT NOT NULL, "authorId" TEXT NOT NULL,
  "comment" TEXT NOT NULL, "progress" INTEGER NOT NULL, "capturedAt" DATETIME NOT NULL, "approvalStatus" TEXT NOT NULL DEFAULT 'PENDING',
  "approvedById" TEXT, "approvedAt" DATETIME, "rejectionReason" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, "deletedAt" DATETIME,
  FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("scheduleItemId") REFERENCES "ScheduleItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Task" (
  "id" TEXT NOT NULL PRIMARY KEY, "type" TEXT NOT NULL, "projectId" TEXT NOT NULL, "scheduleItemId" TEXT, "targetReportId" TEXT,
  "creatorId" TEXT NOT NULL, "assignedToId" TEXT, "title" TEXT NOT NULL, "content" TEXT NOT NULL, "trade" TEXT,
  "priority" TEXT NOT NULL DEFAULT 'NORMAL', "status" TEXT NOT NULL, "dueAt" DATETIME,
  "unreadForAdmin" INTEGER NOT NULL DEFAULT 1, "unreadForAssignee" INTEGER NOT NULL DEFAULT 0, "unreadForCreator" INTEGER NOT NULL DEFAULT 0,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL, "deletedAt" DATETIME,
  FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("scheduleItemId") REFERENCES "ScheduleItem"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY ("targetReportId") REFERENCES "Report"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY ("creatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Photo" (
  "id" TEXT NOT NULL PRIMARY KEY, "reportId" TEXT, "taskId" TEXT, "storageKey" TEXT NOT NULL, "mimeType" TEXT NOT NULL,
  "byteSize" INTEGER NOT NULL, "originalName" TEXT NOT NULL, "capturedAt" DATETIME NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "deletedAt" DATETIME,
  FOREIGN KEY ("reportId") REFERENCES "Report"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS "Photo_storageKey_key" ON "Photo"("storageKey");

CREATE TABLE IF NOT EXISTS "TaskMessage" (
  "id" TEXT NOT NULL PRIMARY KEY, "taskId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "body" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "deletedAt" DATETIME,
  FOREIGN KEY ("taskId") REFERENCES "Task"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Notification" (
  "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "href" TEXT,
  "readAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "AuditLog" (
  "id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL,
  "beforeJson" TEXT, "afterJson" TEXT, "ipAddress" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "ScheduleItem_projectId_parentId_idx" ON "ScheduleItem"("projectId", "parentId");
CREATE INDEX IF NOT EXISTS "Report_projectId_approvalStatus_idx" ON "Report"("projectId", "approvalStatus");
CREATE INDEX IF NOT EXISTS "Task_projectId_type_status_idx" ON "Task"("projectId", "type", "status");
CREATE INDEX IF NOT EXISTS "AuditLog_entityType_entityId_idx" ON "AuditLog"("entityType", "entityId");
